# Generated by Django 3.0.3 on 2020-08-18 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='photo',
        ),
    ]
