# Generated by Django 3.0.3 on 2020-08-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Image',
        ),
    ]
